function funcao1()
{
alert("Eu sou um alert!");
}

function input(){
    $('body').append('<div>\
                                <input id=entrada type="text" name="campo[]">\
                                \
                                </div><span id="saidaTxt">Nenhum resultado...</span>');



// Code goes here
var busca = null;
var array = ["(Poscomp 2012) - Seja o espaço vetorial V = R2. Com relação a esse espaço, assinale a alternativa correta.R: V é soma direta de S1 = {(x, y) ∈  R2|(x, y) = (x, 0)} e S2 = {(x, y) ∈  R2|(x, y) = (0, y)} ",
"Seja A um conjunto e seja ~ uma relação entre pares de elementos de A. Diz-se que ~ é uma relação de equivalência entre pares de elementos de A se as seguintes propriedades são verificadas, para quaisquer elementos a, a’ e a’’ de A:(i) a ~ a;(ii) se a ~ a’, então a’ ~ a;(iii) se a ~ a’ e a’ ~ a’’, então a ~ a’’.Uma classe de equivalência do elemento a de A com respeito à relação ~ é o conjuntoa = {xÎ A : x ~ a}O conjunto quociente de A pela relação de equivalência ~ é o conjunto de todas as classes de equivalência relativamente à relação ~, definido e denotado como a seguir:A/~=  {a : a Î A}A função p: A ® A/~ é chamada projeção canônica e é definida como p(a) = a, aÎ AConsiderando as definições acima, analise as afirmações a seguir.I. A relação de equivalência ~ no conjunto A particiona o conjunto A em subconjuntos disjuntos: as classes de equivalência.II. A união das classes de equivalência da relação de equivalência ~ no conjunto A resulta no conjunto das partes de A.III. As três relações seguintes: =, mod n, ³ são relações de equivalência no conjunto dos números inteiros Z .IV. Qualquer relação de equivalência no conjunto A é proveniente de sua projeção canônica.É correto apenas o que se afirmar em:R- I e IV",
"Sejam os conjuntos A = {1, 3, 5}, B = {3, 1} e C = {3, 5, 7}. A alternativa que representa o conjunto X =A ∩ B ∩ C é:R-X = {3}",
"Considere os conjuntos A = {2, 4, 10} e B = {4, 6, 8}. O conjunto X = A – B é:R-{2, 10}",
"Considere os conjuntos A = {2, 4, 10} e B = {4, 6, 8}. O conjunto X = B – A é:R-{6, 8}",
"Considere o conjunto X = {a, b}. A alternativa que representa o conjunto 2X é:R-{ {  }, {a}, {b}, {a, b}}",
"Considere os  conjuntos A = {7, 8, 9} e B = {7, 9}. Assinale a alternativa que apresenta o conjunto X = 2A– 2B.R-X = {{8}, {7,8}, {8,9}, {7,8,9}}",
"Considere A = {1, 3, 9} e B = {b, c, d}. Assinale a alternativa que apresenta o conjunto C, produto cartesiano de A x B.R- {(1, b), (1, c), (1, d), (3, b), (3, c), (3, d), (9, b), (9, c), (9, d)}",
"Considerando o conjunto A = {1, 2, 3, 4, 5, 6}, qual opção corresponde a uma partição desse conjunto?R-{{1}, {2}, {3}, {4}, {5}, {6}}",
"Um professor de Matemática, ao lecionar Teoria dos Conjuntos em uma certa turma, realizou uma pesquisa sobre as preferências clubísticas de seus n alunos, tendo chegado ao seguinte resultado:23 alunos torcem pelo Paysandu Sport Club;23 alunos torcem pelo Clube do Remo;15 alunos torcem pelo Clube de Regatas Vasco da Gama;6 alunos torcem pelo Paysandu e pelo Vasco;5 alunos torcem pelo Vasco e pelo Remo.Se designarmos por A o conjunto dos torcedores do Paysandu, por B o conjunto dos torcedores do Remo e por C o conjunto dos torcedores do Vasco, todos da referida turma, teremos, evidentemente, A ∩ B = {  }. Concluímos que o número n de alunos desta turma éA 	49B 	50C 	47D 	45E 	46 R-50",
"Poscomp 2002 questão 2: Seja o conjunto A = {x ∈ R; |x| >= 1 }. Qual das alternativas é  uma partição do conjunto A.R-{x <  -1 }, {x > 1}, {-1, 1}",
"Considerando as relações x R y⇔ x | y (x divide y) no conjunto M = {1, 2, 3, 6, 8, 9} e  z B t   ⇔ z | t(z divide t) no conjunto N = {1, 3, 6, 12, 24}, atribua V (verdadeiro) ou F (falso) às afirmativas a seguir( ) A cardinalidade de R é igual a de  B( ) R é uma relação de ordem parcial( ) R é uma relação de ordem total( ) B é uma relação de ordem parcial( )  B é uma relação de ordem totalAssinale a alternativa que contém, de cima para baixo, a sequência corretaR-V, V, F, F, V.",
"Considerando o conjunto A = {1, 2, 3, 4, 5, 6}, qual opção corresponde a uma partição desse conjunto?R-{{1}, {2}, {3}, {4}, {5}, {6}}",
"Um professor de Matemática, ao lecionar Teoria dos Conjuntos em uma certa turma, realizou uma pesquisa sobre as preferências clubísticas de seus n alunos, tendo chegado ao seguinte resultado:23 alunos torcem pelo Paysandu Sport Club;23 alunos torcem pelo Clube do Remo;15 alunos torcem pelo Clube de Regatas Vasco da Gama;6 alunos torcem pelo Paysandu e pelo Vasco;5 alunos torcem pelo Vasco e pelo Remo.Se designarmos por A o conjunto dos torcedores do Paysandu, por B o conjunto dos torcedores do Remo e por C o conjunto dos torcedores do Vasco, todos da referida turma, teremos, evidentemente, A ∩ B = {  }. Concluímos que o número n de alunos desta turma éA 	49B 	50C 	47D 	45E 	46R-50",
"Poscomp 2002 questão 2: Seja o conjunto A = {x ∈ R; |x| >= 1 }. Qual das alternativas é  uma partição do conjunto A.R-{x <  -1 }, {x > 1}, {-1, 1}",
"Considerando as relações x Ry⇔ x | y (x divide y) no conjunto M = {1, 2, 3, 6, 8, 9} e  z B t⇔ z | t(z divide t) no conjunto N = {1, 3, 6, 12, 24}, atribua V (verdadeiro) ou F (falso) às afirmativas a seguir( ) A cardinalidade de R é igual a de  B( ) R é uma relação de ordem parcial( ) R  é uma relação de ordem total( ) B é uma relação de ordem parcial( )  B é uma relação de ordem totalAssinale a alternativa que contém, de cima para baixo, a sequência corretaR-	V, V, F, F, V.",
"Todos os convidados presentes num jantar tomam chá ou café. Treze convidados bebem café, dez bebem chá e 4 bebem chá e café. Quantas pessoas tem nesse jantar.R-19",
"Para cada n ∈ N seja Dn = (0, 1/n), onde  (0, 1/n) representa o intervalo aberto de extremos 0 e 1/n. O conjunto diferença D3 − D20 é igual a:R-[1/20, 1/3)",
"Fundamentada na questão 13 ENADE 2008 Considerando o conjunto A = {1, 2, 3, 4, 5, 6},  I Corresponde uma particção de A P = {{1}, {2}, {3}, {4}, {5}, {6}}porqueII A intersecção entre os subconjuntos  elencados é vazia;Tem se que:R-I e II são verdadeiras e II justifica I",
"Considere-se o seguinte alfabeto:A = { *, &, ?, ! }Qual a alternativa que apresenta uma palavra não definida sobre o alfabeto?R-asterisco.",
"A Linguagem gerada por uma gramática é um conjunto que pode se apresentar com um número infinito de elementos.",
"Considere as cadeias: w = xxyyzz e v = zzyx. Considere as seguintes afirmações:I – wR = vRII- xxy é uma subpalavra de wIII – zz é prefixo de vIV – yx é sufixo de v.Estão corretas as afirmações:R-Apenas II, III e IV;",
"Considere a seguinte gramática: A gramática:G = ({S, D}, {0,1,2,..., 9}, P, S), ondeP = { S ® D | DS,D ® 0 | 1 | ...| 9} Assinale a alternativa incorretaR-Não gera nenhuma linguagem, pois os terminais são apenas numéricos",
"	Uma Linguagem Formal é um conjunto de palavras sobre um alfabeto.R- ",
"Se um alfabeto A, A = {a, b}, então o conjunto Fechamento Recursivo é finito.",
"Considere a gramática G = (V, T, P, A) onde:V = {A, B, C, D, E}T = {0, 1}P = { A ® 0B | 1C;        B ® 0B | 1D| e        C®0C | 1C        D ®1C|0E        E® 0C | 1D | e} Onde o símbolo e é a palavra vazia.Assinale a palavra gerada por G:",
"Considere a seguinte gramática G = (V, T, P, S) onde:V = {X, B, C, S}T = {0}P  = { S ® X; X® YZ | 0; Y ® X; Z ®e }Apresente a alternativa que representa a Linguagem gerada por G:R- L(G) = {0}",
"Considere a seguinte gramática G = (V, T, P, E), onde :V = {E, T, F}T = {[, ], , +, *, x}P = { E ®T | E + T; T ® F | T * F; F ®[E] | x}E é o símbolo inicial da gramática:Sabendo-se que L(G) denota a Linguagem gerada pela gramática G, considere as seguintes afirmações:I - x * x + x Î L(G);II – [x*x] + x Î L(G);III – x * [x + x] Î L(G);IV – [x+x+x+x] Ï L(G). Estão corretas as afirmações:R-Apenas I, II e III;",
"Considere a gramática G definida pelas regras de produção abaixo, em que os símbolos não-terminais são S, X e Y, e os símbolos terminais são x e y.S® XY | YXX® xY | xY ® yX| y Com relação a esta gramática, é correto afirmar que:R-A palavra yxy pertence à linguagem gerada pela gramática G;",
"Considere a gramática a seguir, em que S, A e B são símbolos não-terminais, 0 e 1 são terminais e e é a cadeia vazia.S ® 1S | 0A | eA ® 1S | 0B | eB ® 1S | e        A respeito dessa gramática, analise as afirmações a seguir:I.                   Nas cadeias geradas por essa gramática, o último símbolo é 1.II.                O número de zeros consecutivos nas cadeias geradas pela gramática é, no máximo, dois.III.             O número de uns em cada cadeia gerada pela gramática é maior que o número de zeros.IV.             Nas cadeias geradas por essa gramática, todos os uns estão à esquerda de todos os zeros.É correto apenas o que se afirma em:R-II.",
"Seja a linguagem, onde e representa a sentença vazia:S ® AB | CDA ® a | eB ® b | fC ® c | gD ® h | iQual o conjunto de terminais que podem começar sentenças derivadas de S ?R-{a, b, f, c, g}",
"Poscomp 2002 – questão 67 - Para a gramática a seguir, qual o conjunto de terminais que pode aparecer como primeiro terminal após o não-terminal A, em qualquer forma sentencial gerada pela gramática abaixo (isto é, não necessariamente imediatamente após A), onde ε representa a sentença vazia?S → ABCDdA → aA |  εB→ bC |  εC → cD |  εD → eR-{b,c,d,e}",
"Duas gramáticas são equivalentes se e somente se geram a mesma linguagem. Considere uma gramática definida sobre o alfabeto Σ = {x, y} cujas produções são:A → Ax | y. Assinale a alternativa que apresenta produções que gerab a mesma linguagem .R-A → yB; B → xB |ε",
"Qualquer expressão aritmética binária pode ser convertida em uma expressão totalmente parentizada, bastando reescrever cada subexpressão binária a Ä b como (a Ä b), em que Ä denota um operador binário. Expressões nesse formato podem ser definidas por regras de uma gramática livre de contexto, conforme apresentado a seguir. Nessa gramática, os símbolos não-terminais E, S, O e L representam expressões, subexpressões, operadores e literais, respectivamente, e os demais símbolos das regras são terminais.E ® ( S O S )S ® L | EO ®  + | - | * | /L ® a | b | c | d | eAssinale a alternativa que apresenta uma derivação incorretaR-EÞ (SOS) Þ (LOS) Þ(b O S) Þ(a - S) Þ(a -  E) Þ (a- (SOS)) Þ (a- (LOS))  Þ (a - (bOS)) Þ (a - (b/S)) Þ (a - (b/L)) Þ (a - (b/c))",
"S → ABCDdA → aA |  εB→ bC |  εC → cD |  εD →  eTem-se que:I.  O conjunto de terminais que pode aparecer como primeiro terminal após o não-terminal A, em qualquer forma sentencial gerada pela gramática abaixo (isto é, não necessariamente imediatamente após A), onde ε representa a sentença vazia é {b, c, d, e}PORQUEII Os símbolos não terminais A, B, C podem ser substituído pela palavra vazia εR-I e II são verdadeiras e II justifica I",
"(c*a [abc]*b[abc]*) | c*Assinale a alternativa que descreve, corretamente, todas as características geradas por essa expressão regularR-Cadeias sobre o alfabeto {a, b, c}, onde o primeiro a precede o primeiro b..",
"Considere-se a seguinte linguagem  L definida sobre o alfabeto A = {a,b,c}L = {w | w = a* b+c }. Não é uma palavra pertencente à Linugagem L:R-aac",
"Considere-se a linguagem L definida sobre o alfabeto A = {a, b, c}, onde L = { w | w = c+ (a+b*)* c*}.É uma palavra pertencente a L:R-cabc",
"Um autômato finito determinístico pode ser representado pela  quíntupla:M= (S, s0, F, A, g)OndeA: alfabeto dos símbolos de entrada;s0: estado inicial;F: conjunto de estados finais;S: conjunto de estados do autômato;g: função programa ou função de transição g:   S ´ A ® S.A função g para o autômato reconhecedor da linguagem  L definida sobre oalfabeto A = {a, b}L =  {w | w = a*b} é:onde q0 é o estado inicialF = {q1}S = {q0, q1}R-g = {((q0, a), q0), ((q0, b), q1)}",
"Considere uma máquina M definida sobre uma quíntupla:M= (S, s0, F, A, g)ondeA: alfabeto dos símbolos de entrada;s0: estado inicial;F: conjunto de estados finais;S: conjunto de estados da máquina;g: função programa ou função de transição g: A ´ S2A Considere-se o seguinte autômato M = (S, q0, F, A, g), onde:S = {q0,q1,q2,q3};q0 é o estado inicial,F = {q1, q3}A = {a,b}g = { ((q0, a), {q1,q2}), ((q2, b), {q3}), ((q3,a), {q2})}Pode-se afirmar que:R- M representa um autômato finito não-determinístico pois existem duas transições com origem no estado q0 , que consomem o símbolo do alfabeto a, e estados destinos distintos:q1 e q2;",
"Um autômato finito determinístico pode ser representado pela  quíntupla:M= (S, s0, F, A, g)onde:A: alfabeto dos símbolos de entrada;s0: estado inicial;F: conjunto de estados finais;S: conjunto de estados do autômato;g: função programa ou função de transição g:   S ´ A ® S.Seja  L, uma Linguagem definida sobre o alfabeto A = {a, b}L = {w | w possui um número par de a e b} é:Assinale a alternativa que represente a função de transição de um autômato reconhecedor desta Linguagem, com estado inicial em q0.R- g = {((q0, b), q1), ((q0, a), q2), ((q1, a), q3), ((q1, b), q0), ((q2, a), q0), ((q2, b), q3), ((q3, a), q1), ((q3, b), q2)}",
"Considere a seguinte Gramática Linear à Direita:G = ({S, A, B}, {a, b}, P, S)onde P  é tal que: P = {S®aA; A ® bB|e, B ® aA; }A representação algébrica do Autômato finito que reconhece a linguagem gerada por G é M = ({a,b}, (S, A, B), g, S, {A}) onde g, função de transição é dada por:R- g = {((S, a), A), ((A, b), B), ((B, a), A)};",
"Considere uma linguagem L definida sobre o alfabeto A = {a, b}. Assinale a linguagem L reconhecida pelo autômato  M = ({qo, q1, q2, qf}, q0, g, A, {qf}), cuja  função de transição é dada por:g = {((q0, b), q0), ((q0, a), q1), ((q1, a), q2), ((q2, a), qf), ((qf, a), qf), ((qf, b), qf)}R-	L = {w | w possui aaa como subpalavra}",
"Considere a gramática G = (V, T, P, A) onde:V = {A, B, C, D, E}T = {0, 1}P = { A ® 0B | 1C;        B ® 0B | 1D| e        C®0C | 1C        D ®1C|0E        E® 0C | 1D | e} Onde o símbolo e é a palavra vazia.Considere-se um autômato M = (S, qa, F, A, g), onde:S = {qa, qb, qc, qd, qe, qf}qa é o estado inicial;F = {qb, qe}A = {0, 1} Pede-se a função programa g que completa a definição formal do autômato M, tal que seja o reconhecedor da mesma Linguagem gerada pela gramática G acima:R-g = {((qa, 0), qb), ((qa, 1), qc), ((qb, 0), qb), ((qb, 1), qd), ((qc, 0), qc), ((qc, 1), qc), ((qd, 1),qc), ((qd, 0), qe), ((qe, 0), qc), ((qe, 1), qd)}",
"Considere as seguintes afirmações:I – A Classe dos Autômatos Finitos Determinísticos é equivalente à Classe dos Autômatos Finitos Não-Determinísticos.II – Para uma particular Linguagem Regular, pode não existir uma gramática geradora da mesma.III – Uma Linguagem Regular é sempre finita.IV – Um Autômato Finito a ser minimizado deve ser determinístico;São verdadeiras as afirmações:R-Apenas I e IV;",
"Considere a expressão regular: (10* | 11)*(0*1)*. Trata-se de uma palavra pertencente ao conjunto dado:R-10000001",
"Considere a seguinte gramática G, (V, T, P, S), onde:V é o conjunto de símbolos não terminais com V = {S, A, B, C}, sendo S o símbolo incial da gramática.T é o conjunto de símbolos terminais e T = {0, 1 }P é o conjunto de regras ou produções , a saber:P = {    S ® ABC | 0;        A ®1A | 0    B ® B0S | A    C® 01C |01 }Pode-se afirmar que:R- As As cadeia geradas pelo não-terminal A podem ser representadas pela expressão regular (01)*",
"Considere o autômato M, onde:·         Q é o conjunto de estados e Q = {Q0, Q1, Q2 }·         Q0 é o estado inciail·         F = {Q2 } é o conjunto de estados finais·         å = {a, b} coincide com o alfabeto da Linguagem reconhecidaAinda, a função programa do autômato pode ser representada pela seguinte tabela:Símbolo lidoEstado atualabQ0{Q1}{ }Q1{Q1}{Q1,Q2} Considere as seguintes afirmações:I – Trata-se de um autômato finito não-determinístico.II – As cadeias reconhecidas pelo autômato devem apresentar ao menos uma ocorrência da sub-cadeia (bb).III – O autômato aceita cadeias  cujos prefixos podem ser representados pela expressão regular a*.IV – O autômato aceita cadeias, cujos sufixos podem ser representados pela expressão regular (aa)b*.Estão corretas as afirmações:R-Apenas I, II e III;c)",
"Considere ainda o autômato  M = (Q, q0, S, F, g), ondeQ = {Q0, Q1, Q2, Q3, Q4}Q0 é o estado inicial;F = {Q4}S = {a, b, c}A função programa g é dada por:                                            SímboloEstado atualabcQ0{Q1}--Q1{Q1}{Q2}-Q2{Q3}{Q2, Q3}{Q4}Q3{Q3}{Q3}{Q4} Ou ainda, g pode ser representada como:g = {((q0, a), {q1}), ((q1, a), {q1}), ((q1, b), {q2}), ((q2, b), {q2,q3}), ((q2, a), {q3}), ((q2, c), {q4}), ((q3, a), {q3}), ((q3, b), {q3}), ((q3, c), {q4})}A Linguagen reconhecida por M éR- L (w) = {w | w = a+b+ (a|b)* c}",
"Considere, a seguir, a gramática livre de contexto:S→ aS|Sb|cQual expressão regular gera a mesma linguagem que a gramática definida acima?R-a* c b*",
"Considere a seguinte gramática G, (V, T, P, S), onde: V é o conjunto de símbolos não terminais com V = {S, A, B, C}, sendo S o símbolo incial da gramática.T é o conjunto de símbolos terminais e T = {0, 1 }P é o conjunto de regras ou produções , a saber:P = {    S ® ABC | 0;        A ®1A | 0    B ® B0S | A    C® 01C |01 }Pode-se afirmar que:R-As cadeias  geradas pelo não-terminal A podem ser representadas pela expressão regular (01)*d)    ",
"figura, substituída pela função programa do autômato).Autômatos finitos possuem diversas aplicações práticas como na detecção de seqüências de caractereres em um texto. A função programa abaixo apresenta um autômato que reconhece seqüências sobre o alfabeto S = {a, b, c} e uma gramática livre de contexto que gera um subconjunto de S*, em que l representa o string vazio.Autômato: M =  (S, 0, F, A, g), onde:S = {0, 1, 2, 3, 4, 5}0 é o estado inicial;F = {5}A = {a, b, c} lA função g pode ser representada pela tabela abaixo:gabc010011202300341043055555S ®aS | bS | cS | bAA ® abA | abcBB ® aB | bB | cB | l l  = palavra vazia Analisando a gramática e o autômato acima, conclui-se que:R-A linguagem reconhecida pelo autômato é a mesma gerada pela gramática.",
"figura do autômato substituída pela definição formal)Que cadeia é reconhecida pelo autômato definido como:Autômato: M =  (S, 0, F, A, g), onde:S = {A, B, C, D}A é o estado inicial;F = {B}A = {0,1}A função g pode ser representada pela tabela abaixo:g01ADBBCACBDDABR-111011000",
"Seja å = {a, b}. Uma expressão regular denotando a linguagem:L = {w Î å* tal que toda ocorrência de “a” emw é imediatamente seguida de “b”}é:R-(b | ab)* ",
"questão 36: As seguintes expressões regulares denotam as linguagens P,Q, L e R, respectivamente:. (1 + 10)*, (0 + 01)*, (0 + 1)*, 0(11)* + 1(00)*. Não se pode afirmar que:R-(1 + 0)* \ P = Q",
"Analise as seguintes igualdades de expressões regulares:I. a* = (a*)*II. (a+b)* = (b+a)*III. a*+b* = (a+b)*A análise permite concluir queR-omente as igualdades I e II são verdadeiras.",
"Analise as seguintes igualdades de expressões regulares:I. a* = (a*)*II. (a+b)* = (b+a)*III. a*+b* = (a+b)*A análise permite concluir queR-somente as igualdades I e II são verdadeiras.",
"Q = {q0, q1, q2, q3}, onde q0 é o estado final e F = {q2, q3}, Σ = {a, b} e a relação de transição g, definida como:g(q0, a) ={ q1}; g(q0, ε) ={ q2}; g(q1, a) = {q2,q3}; g(q2, a) = {q3}; g(q2, b) = {q1}; A esse respeito assinale a alternativa FALSA:R-A palavra aba é reconhecida pelo autômato.",
"S → AcBA → cA | aBB→ cB | aAA→εAssinale a alternativa que apresenta a palavra que NÃO pertence à linguagem gerada pela gramática G.R-aaa",
"Seja o autômato finito, que opera sobre o alfabeto Σ = {a, b}Q = {q0, q1, q2, q3}, q0 é estado inicial, F = {q0} e função de transição dada por:g(q0, a) = q1; g(q0, b) = q2; g(q1, a) = q1; g(q1, b) = q3; g(q3, b) = q3; g(q3,ε) = q0;g(q2, a) = q3.Analise as seguintes alternativas:I - O autômato finito é determinístico.II - O autômato finito é não-determinístico.III- O autômato finito reconhece a palavra vazia.A análise permite afirmar que:R-somente a afirmativa I é falsa.",
"Seja o alfabeto Σ = {a, b} e a linguagem regular  L = {w | wÎå* e o nº de a’s em w é par }.Qual das expressões regulares abaixo gera essa linguagem?R-( b* a b* a b* )*",
"Considere, a seguir, a gramática livre de contexto:S ® aS|Sb|cQual expressão regular gera a mesma linguagem que a gramática definida acima?R-a* c b*",
"Questão 42: Assinale a alternativa que apresenta, corretamente, uma expressão regular que denota todas asstringsde a’s e b’s que têm pelo menos dois b’s consecutivos.R-(a+ba)*bb(a+b)* ",
"Considere o autômato M, com a seguinte representação algébrica:Q = {n0, n1, n2, n3, n4, n5, n6, n7, n8, n9}, no é o estado inicial. F = {n9}, O alfabeto é Σ = {a, b, c}. A relação de transição é dada por:g(n0, a) = n1g(n1, ε) = n2,  g(n2, ε) = n3,  g(n3, ε) = n4,  g(n3, ε) = n6,  g(n5, ε) = n8,  g(n7, ε) = n8,  g(n8, ε) = n9,  g(n2, ε) = n9,  g(n8, ε) = n3,   g(n4, b) = n5, g(n6, c) = n7.Assinale a alternativa que apresenta a expressão regular que gera a mesma linguagem reconhecida pelo autômato.R-a(b|c)*",
"G = ({x, y, z}, {S, W, X, Y, Z}, P, S)na qual os membros de P são:S → WZW → X | YX → x | xXY → y | y YZ → zZQual das expressões regulares abaixo corresponde a esta gramática?",
"questão 46 Considere as seguintes afirmações sobre autômatos finitos e expressões regularesI - A classe das linguagens aceita por um Autômato Finito Determinístico (AFD) não é a mesma que um Autômato Finito Não Determinístico (AFND).II - Para algumas expressões regulares não é possível construir um AFD.III - A expressão regular (b+ba)+ aceita os 'strings' de b's e a's começando com b e não tendo dois a's consecutivos.Selecione a alternativa correta.R-Apenas a afirmativa III é verdadeira.",
"Se o estado inicial for também estado final em um autômato finito, então esse autômato:R-Aceita a cadeia vazia",
"Autômatos Finitos são dispositivos geradores de Linguagens Regulares.R-incorreta",
" Um autômato mínimo é um autômato que apresenta o menor número de estados. O Autômato mínimo para uma linguagem é único a menos de isomorfismo.R-correta",
"Assinale qual a alternativa que não diz respeito à minimização de um autômato finito:R-A função programa g deve ser tal que especifique duas transições que apresentem o mesmo estado origem, consomem o mesmo símbolo  e  apresentam estados destino distintos.",
"Considere as seguintes afirmações:I – A Classe dos Autômatos Finitos Determinísticos é equivalente à Classe dos Autômatos Finitos Não-Determinísticos.II – Para uma particular Linguagem Regular, pode não existir uma gramática geradora da mesma.III – Uma Linguagem Regular é sempre finita.IV – Um Autômato Finito a ser minimizado deve ser determinístico;São verdadeiras as afirmações:R- Apenas I e IV;",
"Considere as seguintes afirmações:I – Dados dois geradores de liguagens (gramáticas) e dois reconhecedores de linguagens, pode-se verificar se os dois geradores de Linguagens são equivalentes se os autômatos mínimos dos correspondentes reconhecedores são iguais.II – Existe um algoritmo polinomial, para o qual, dada uma expressão regular, pode-se construir um autômato finito não-determinístico equivalente.III – Existe um algoritmo polinomial , tal que para um determinado autômato finito determinístico é possível construir um autômato finito determinístico com o menor número de estados, possível.Estão corretas as afirmações:R-  I, II e III;",
"Uma máquina de Moore M é um Autômato Finito Determinístico com saídas associadas aos estados. É representada por um 7-tupla:M = (A, Q, g, q0, F, g, gs, S), onde:A = alfabeto dos símbolos de entrada;Q = conjunto de estados possíveis do autômato o qual é finito;g: função programa ou função de transiçãoq0: estado inicial ;F = conjunto de estados finais;gs=função de saída. Considere a seguinte tabela que representa as funções g e gs de uma Máquina de Moore.Estado atualPróximo estadoSaída Entrada01 S0S1S00S1S2S11S2S2S01 Considere-se a cadeia de entrada 01101. Qual é a saída obtida, sabendo-se que o processamento da mesma inicia-se no estado s0?R-01111;",
"Considere a seguinte tabela que representa a função programa de uma máquina de estados finitos:Estado atualPróximo estadoEntradaxyq0Q2Q0q1Q2Q1q2Q2Q0 Se o estado q0 for o estado inicial, os estados inacessíveis são:.R-apenas q1",
"Considere a seguinte tabela que representa função programa de uma máquina de estados finitos.Estado atualPróximo estadoEntradaabq0q3Q6q1q4Q2q2Q4Q1q3q2Q0q4Q5Q0q5Q3Q5q6Q4Q2 Considere as seguintes afirmações:I – São equivalentes os estados q1, q2 e q5.II – São equivalentes os estados q6 e q0.III – São equivalentes os estados q3 e q4. Estão corretas as afirmações:R-Apenas I e III;",
"Considere o seguinte autômato finito determinístico: M = (Q, q0, A, F, g), onde:Q = {Q1, Q2, Q3 } (conjunto de estados).F = {Q3} (conjunto de estados finais);A = {a, b} (alfabeto de entrada);Q1 é o estado inicial;A função programa g é representada na tabela abaixo:Estado atualPróximo estadoEntradaabQ1Q1Q2Q2Q2Q3Q3Q3Q1Considere o seguinte algoritmo descrito em pseudo-código não estruturado:q1:       x= get_símbolo( );            se x = fim de arquivo então rejeita;            senão se x = a então goto q1;            senão se x = b então goto q2;q2:       x = get_símbolo( );            se x = fim de arquivo então rejeita;        senão se x = a então go to q2;        senão se x = b então goto q3;q3:       x = get_símbolo( );    se x = fim de arquivo então aceita;    senão se x = a então goto q3;    senão se x = b então goto q1;Considere-se  o pseudo-código , bem como a especificação formal do autômato M. Leve-se em conta as seguintes afirmações:I – Um autômato finito determinístico é um algoritmo eficiente para decidir se uma dada cadeia pertence à Linguagem para a qual o autômato foi projetado.II – Para descrever um autômato finito determinístico como um algoritmo tal que para cada estado q Î Q, são necessárias |Q| + 2 instruções, das quais a primeira obtém o próximo símbolo de entrada a ser analisado e cada uma das outras é responsável por realizar a ação correta para cada valor particular do símbolo de entrada, bem como, o símbolo de fim de arquivo, correspondente ao fim da cadeia de entrada. III – Se L é uma Linguagem regular, então existe um algoritmo que testa em um tempo O(|w|), se a palavra w Î A*, está em LEstão corretas as afirmações:R- I, II e III;",
"Estado Inicial A, estados de aceitação C e Dg (A, b) = Bg(B, a) = Cg (C, a) = D",
"Considere a seguinte propriedade sobre uma linguagem formal L: “Existe um número p ≥ 0, tal que para qualquer palavra w ∈L, |w| ≥ p, existem palavras x, y e z, com  y ¹ ε |xy| ≤ p, tais que, para qualquer inteiro i ≥ 0, a palavra xyiz ∈L”. Com base no enunciado e nos conhecimentos sobre o tema, atribua V (verdadeiro) ou F (falso) para as afirmativas a seguir.( ) Se L é aceita por AFND, então L satisfaz a propriedade acima.( ) A linguagem formada de 1’s e 0’s com igual quantidade de ocorrências das palavras 01 e 10 satisfaz a propriedade acima.( ) A propriedade acima é falsa para a linguagem 0i1k2j/i, j, k ≥ 0 e se i = 1, então k = j.( ) A linguagem {anbncn/n ≥ 0} não satisfaz a propriedade acima.( ) A linguagem {anbm/n,m ≥ 0 e n¹ m} satisfaz a propriedade acima.R- V, V, F, V, F.",
"Seja um Autômato Finito Não Determinístico (AFN) com 6 estados. Aplicando-se o algoritmo de conversãode um AFN para um Autômato Finito Determinístico (AFD), em quantos estados, no máximo, resultaria o AFD considerando-se os estados inúteis?R-64",
"Fundamentado na quesão 41- Poscomp 2012: Seja um Autômato Finito Não Determinístico (AFN) com 5 estados. Aplicando-se o algoritmo de conversãode um AFN para um Autômato Finito Determinístico (AFD), em quantos estados, no máximo, resultaria o AFD considerando-se os estados inúteis?R-32",
"Quanto ao fechamento para linguagens livres de contexto, atribua V(verdadeiro) ou F(falso) às operações a seguir:( )  concatenação( ) complemento( ) homomorfismo( ) intersecção( ) reversoAssinale a alternativa que contém, de cima para baixo, a sequência corretaR- V, F, V, F, V",
"Sobre o lema do Bombeamento (pumping lemma) para linguagens regulares, considere as afirmativas a seguir:I. Se o alfabeto ?A = {a, b}, então pode-se provar por absurdo, por meio do Bombeamento, que a linguagem L1 = {w ? ?A*| w termina com b} não é regular.II. Se o alfabeto ?A = {a, b}, então pode-se provar por absurdo, por meio do Bombeamento, que a linguagem L2 = {(an)2 | n ≥ 1} não é regular.III. Se o alfabeto ?A = {a, b}, então pode-se provar por absurdo, por meio do Bombeamento, que as linguagens L3 = { an! | n ≥ 1},L4 = {anbamban+m | n, m ≥1} e L5 = {am+1bn+1 | 2 ≤n≤m≤3n } não são regulares.IV. Se a linguagem for do tipo 3, então aplica-se o Bombeamento.Assinale a alternativa correta:R-Somente as afirmativas II, III e IV são corretas.",
"Sobre as linguagens regulares, considere as afirmativas a seguir:I As linguagens regulares podem ser expressas por máquinas de Moore e de Mealy.II. As linugagens regulares podem ser expressas por um autômato finito.III, Se A e B são linguagens regulrares, então A Ç B também é.IV Seja B = {ba, na}. Pode-se dizer que B* = {  € , ba, na, baba, naba, anab, nana, aban, bababa, babana,banaba, banana, nababa, nabana, nanana, abanba, babababa...}Observação:€ = palavra vaziaAssinale a alternativa correta:R-Somente as afirmativas I, II e III são corretas.",
"Seja a máquina de estados finitos representada pelo diagrama acima, determine o modelo (Mealy ou Moore) e o circuito digital ao qual ela corresponde.R-Modelo de Mealy correspondente a um contador módulo 5.",
"Em uma Gramática Livre de Contexto as produções são necessariamente da forma:R-	A® a, onde A Î V e a Î (V ÈT)*.",
"Em uma Gramática Livre de Contexto as produções podem se apresentar no lado esquerdo com:R-apenas um não-terminal;",
"Em uma Gramática Livre de Contexto as produções são necessariamente da forma:R-	A® a, onde A Î V e a Î (V ÈT)*.R-L = {an bn | n > 0 };",
"Considere a gramática G definida pelas regras de produção abaixo, em que os símbolos não-terminais são S e A, e os símbolos terminais são 0 e 1.S ®A1AA®0|1| A1ACom relação a esta gramática, é correto afirmar que:R-A palavra 01010 gerada por esta gramática e apresenta duas árvores de derivação;",
"Considere a seguinte gramática G = (V, T, P, S), onde:V = {S}T = {x, y}P = {S ® xSy |  e} A Linguagem gerada por G éR-L(G) = {w | w = xn yn, n ³ 0 }",
"Considere a seguinte gramática livre de contexto:G =({S}, {a, b}, P, S), onde:P = {S ® SS | aSa | bSb | e }Assinale a alternativa correta:R-Trata-se de uma Gramática ambígua pois existe ao menos uma palavra gerada por esta Gramática que apresenta duas árvores de derivação.",
"As formas normais estabelecem restrições rígidas na definição das produções, sem reduzir o poder de geração das Gramáticas Livres do Contexto. São usadas principalmente no desenvolvimento de algoritmos e na prova de teoremas”.  Seja uma Gramática G = (V, T, P, S), onde:V = conjunto dos símbolos não-terminais;T = conjunto dos símbolos terminais;P = conjunto das regras ou produções;S Î V é o símbolo inicial da gramática. Diz-se que a gramática G se apresenta na Forma Normal de Chomsky (FNC), se todas as suas produções forem da forma:R-A ® BC ou A® a, onde A, B, C Î V e a Î T.",
"As formas normais estabelecem restrições rígidas na definição das produções, sem reduzir o poder de geração das Gramáticas Livres do Contexto. São usadas principalmente no desenvolvimento de algoritmos e na prova de teoremas”.  Seja uma Gramática G = (V, T, P, S), onde:V = conjunto dos símbolos não-terminais;T = conjunto dos símbolos terminais;P = conjunto das regras ou produções;S Î V é o símbolo inicial da gramática.Diz-se que a gramática G se apresenta na Forma Normal de Greibach (FNG), se todas as suas produções forem da forma:R-A® aa, onde A Î V , aÎ T e a Î V+.",
"Considere a gramática G definida pelasregras de produção ao lado, em que os símbolos não-terminais são S, A e B, e os símbolos terminais são a e b.S ® ABAB ®AABA ® aB ® b Considere as seguintes afirmações:I - A gramática G é uma gramática livre de contexto.II - a cadeia aabbb é gerada por essa gramática.III - a gramática G gera a cadeia nula.IV – As palavras da Linguagem L(w) = {w | w = a+b} pertencem à Linguagem gerada pela gramática G.Estão corretas as afirmações:R-Apenas IV;",
"Considere a gramática G = (V, T, P, I), onde:V = {I, A}T = {a, b}P = { I ® AA;A ® AAA | a| bA| Ab}Considere as seguintes afirmações sobre G:I – Trata-se de uma gramática dependente de contexto;II – Trata-se de uma gramática ambígua;III – Gera palavras da Linguagem L1 (w) = {w | w = bmabnabp, m>0, n, p >0}Estão corretas as afirmações:R-Apenas II e III;",
"Qual é a linguagem da gramática com as seguintes regras de produçãoS → ASb | cA →aR-{ ancbn | n Î N }",
"O estudo das Linguagens Livres de Contexto, apresenta ampla aplicação no projeto e implementação do Analisador Sintático, módulo funcional de um compilador. Assim sendo, faz-se necessário que no projeto do compilador, uma gramática livre de contexto não apresente qual característica?R-Ambiguidade;",
"As Linguagens Regulares apresentam como dispositivo aceitador de cadeias corretas os autômatos finitos e são geradas por Gramáticas Regulares. Linguagens Regulares também podem ser definidas por expressões regulares. Assinale a alternativa que apresenta uma característica das Linguagens Livres de Contexto que não pode ser processada pelos formalismos ´associados às Linguagens Regulares:R-aninhamentos sintáticos;",
"Considere as seguintes afirmações :I - A intersecção de uma Linguagem Regular com uma Linguagem Livre de Contexto é uma Linguagem Livre de Contexto.II - Toda Linguagem Livre de Contexto é aceita por algum autômato de pilha.III - Toda Linguagem aceita por algum autômato de pilha é Livre de Contexto.IV - Linguagens Livres de Contexto determinísticas são aceitas por autômatos de pilha não-determinísticas.Assinale a alternativa correta:R-As afirmações I, II, III e IV são corretas.",
"I) A → bAA → aAA → εII) B→ BBB → bIII)  C → CaCA → A c AA → acaIV) D → EEEE → FGF → a | aFG → b | bGA esse respeito, assinale a afirmativa FALSA R-A gramática IV é livre de contexto",
"S → AcBA → cA | aBB→ cB | aAA→εAssinale a alternativa que apresenta a palavra que NÃO pertence à linguagem gerada pela gramática G.R-aaa",
"Questão 36: Sejam as linguagens L1 = aibncm/i, n,m ≥ 0 e L2 = anbmcidk/i, n, k,m ≥ 0, com i = mou n = m.Com base nessa informação, é correto afirmar:R-L1 ∩  L2 possui gramática livre de contexto geradora. ",
"Considere a gramática G definida pelasregras de produção ao lado, em que os símbolos não-terminais são S, A e B, e os símbolos terminais são a e b.S ® ABAB ®AABA ® aB ® bR-é possível encontrar uma gramática regular equivalente a G.",
"Fundamentada na questão 39 poscomp 2015A gramática G = ({S, A, B}, {0,1}, P, S), onde P é dado pelas regras de produçãoS → 0AB| 1BAA→0AS | 1A |eB→ 0B | 1BS |eGera uma linguagem queR-pertence à classe  livre de contexto.",
"I) A → bAA → aAA → εII) B→ BBB → bIII)  C → CaCA → A c AA → acaIV) D → EEEE → FGF → a | aFG → b | bGA esse respeito, assinale a afirmativa FALSA R-A gramática IV é livre de contexto. As produções apresentam no lado esquerdo mais de um símbolo não terminal.",
"fundamentada na questão 39 poscomp 2015  A gramática G = ({S, A, B}, {0,1}, P, S), onde P é dado pelas regras de produçãoS → 0AB| 1BAA → 0AS | 1A |eB →  0B | 1BS |eGera umalinguagem queR-é livre de contexto, pois do lado esquerdo das produções ocorre apenas um símbolo não terminal",
"Fundamentado na questão 39 Poscomp 2015 : : A gramática G = ({S, A, B}, {0,1}, P, S), onde P é dado pelas regras de produçãoS → 0AB| 1BAA → 0AS | 1A |eB → 0B | 1BS |eGera umalinguagem queR-Contém a cadeia 0",
"Se L é uma Linguagem Livre de Contexto, então existe um Autômato com  Pilha com controle de aceitação por estados finais com somente dois estados que aceita a Linguagem L.",
"Se    L é uma Linguagem Livre de Contexto, então existe um Autômato de Pilha com controle de aceitação por estados finais com somente três estados.",
"Se L é uma Linguagem Livre de Contexto, então existe um Autômato de Pilha com controle de aceitação por estados finais com somente três estados.",
"Não é pertinente ao formalismo reconhecedor  autômato de pilha:R- lista encadeada.",
"Se L é uma Linguagem Livre de Contexto, então ela é gerada por uma Gramática Regular.",
"Linguagens Livres de Contexto não-regulares exigem para seu reconhecimento algo mais que um autômato finito.  Torna-se necessária uma memória auxiliar para o registro dos fatos da parte já lida do texto de entrada. Não-determinismos também são convenientes para facilitar o emprego da informação anteriormente memorizada no reconhecimento das sentenças. Um autômato para o reconhecimento estrito de linguagens livre de contexto deve ser inspirado nas gramáticas livres de contexto.” (José Neto, J.) . Considere as seguintes afirmações sobre dispositivos reconhecedores de Linguagens Livres de Contexto:I - A definição formal de um reconhecedor de Linguagens Livres de Contexto é fundamentado em estruturas dinâmicas do tipo fila.II - Se L é uma Linguagem Livre de Contexto, então existe um Autômato de Pilha com controle de aceitação por estados finais com somente três estados.III – A definição formal de um autômato de pilha prevê dois alfabetos: o alfabeto dos símbolos de entrada que são armazenados na fita de entrada e  o alfabeto de pilha que podem ser armazenados na memória auxiliar organizada em pilha.Estão corretas as afirmações:R-Apenas II e III;",
"A Classe das Linguagens Livre de Contexto ou tipo 2 compreende um universo mais restrito comparativamente com a Classe das Linguagens Regulares;",
"O estudo das Linguagens Livre de Contexto apresentam sua aplicação na especificação dos Analisadores Sintáticos das Linguagens de Programação.",
"Não se pode provar que a linguagem L = {an c bn | n > 0 }é livre de contexto.",
"Um autômato de Pilha Não-Determinístico é definido pela sêxtupla M = ( Q, A, g, q0, F, V), onde:A = alfabeto de símbolos de entrada;Q = conjunto de estados possíveis do autômato o qual é finito;g é a função programa ou de função de transição:g: Q ´(AÈ {e, ?} ´ (VÈ {e, ?}) ® 2Q ´ V*a qual é uma função parcial;q0 é o estado incial;F é o conjunto de estados finais;V é o alfabeto auxiliar ou alfabeto de pilha;Considere o seguinte autômato de pilha M = ( Q, A, g, q0, F, V), onde:Q = {q0, qf}F = {qf}A = {a, b}V = {a}g = {((q0, a, e), (q0, a)), ((qo, b, e), (q0, a)), ((q0, a, e), (qf, e)), ((qf, a, a), (qf, , e)), (qf, b, a), (qf, e)}Considere as seguintes afirmações:I - baa é uma palavra da Linguagem reconhecida pelo autômato M.II – aa, abbb são palavras que não pertencem à Linguagem reconhecida pelo autômato M.III – M reconhece a Linguagem L(w) = {w| w = an bn, n > 1}Estão corretas as afirmações:Apenas I e II;",
"Seja a linguagem forma lL = {anb2nc, n ≥ 0}. Analise as seguintes assertivas.I - L é uma linguagem livre de contexto.II - A gramática G = ({S,X}, {a, b, c}, {s → Xc, X → aXbb| ε }, gera a linguagem L.III - L não pode ser reconhecida por um autômato com pilha.A análise permite concluir que estão CORRETASR-apenas as assertivas I e",
"Considerando as linguagens L1 = {alcmbn; l ³ 0, n ³0} e L2 = { alcmbn; l³ 0, n ³ 0 e n = l + m} sobre  o alfabeto Σ= {a, b, c} considere as afirmativas a seguir.I. L1 é uma linguagem regular.II. L2 é uma linguagem regular.III. Existe um autômato de pilha determinístico que reconhece L1.IV - A Linguagem L2 pode ser ferada pela G = ({X, T}, {a, b, c}. { X → a X b. X → Y, Y → cYb,  Y → λ}, X), onde λ é a palavra vaziaR-Somente as afirmativas I, III e IV são corretas.",
"Em relação a autômatos e linguagens, podemos afirmar:R-Existem linguagens reconhecidas por autômatos de pilha não determinísticos que não podem ser reconhecidas por autômatos de pilha determinísticos.",
"A gramática G = ({S, A, B}, {0,1}, P, S), onde P é dado pelas regras de produçãoS → 0AB| 1BAA → 0AS | 1A | eB → 0B | 1BS | eGera uma linguagem que:R-Pode ser aceita por um autômato com pilha",
"Considerando as linguagens L = {0n1n2i | n ≥ 0 e i ≥ 0 } e M = {0i 1n2n |  n ≥ 0 e i ≥ 0  }, podese afirmar que:R-A linguagem L U M pode ser gerada por uma gramática livre de contexto",
"Considerando as linguagens L = {0n1n2i | n ≥ 0 e i ≥ 0 } e M = {0i 1n2n |  n ≥ 0 e i ≥ 0  }, podese afirmar que:R-A linguagem L U M pode ser gerada por uma gramática livre de contexto, pois apresenta palavras cujo número de ocorrências do símbolo  1 é coincidente com o número de ocorrências do símbolo 0 ou com o número de ocorrências do símbolo 2.",
"Fundamentada na questão 40 poscomp 2015:Questão 40: Considerando as linguagens L = {0n1n2i | n ≥ 0 e i ≥ 0 } e M = {0i 1n2n |  n ≥ 0 e i ≥ 0  }, pode-se afirmar que:R-As linguagens L e  M podem ser geradas por gramáticas livres de contexto.",
"Considerando as linguagens L = {0n1n2i | n ≥ 0 e i ≥ 0 } e M = {0i 1n2n |  n ≥ 0 e i ≥ 0  }, pode-se afirmar que:R-A intersecção das linguagens L e M é dependente de contexto",
"Trata-se de uma característica não-desejável nas Gramáticas Livres de Contexto, quando se implementa um algoritmo de análise top-down:R-recursividade à esquerda",
"Considere a seguinte gramática G = (V, T, P, S), onde:V = {S, A}T = {a, b}P = { S ®AA|AS|b        A® SA | AS | a }Assinale a alternativa que representa o triângulo de derivação para a palavra aba, ao se aplicar o algoritmo CYK:A)     R-S,A A,S A A S A a b a",
"Considere a seguinte gramática G = (V, T, P, S), onde:V = {S, A, B,C},T = {a, b}P = { S ®AB | BC        A® BA | a    B® CC | b        C ® AB | aAssinale a alternativa que representa o triângulo de derivação para a palavra baaba, ao se aplicar o algoritmo CYK.R- S, A, C-S, A, C-B  BA, S B S, C S, A B A, C A, C B A, C b a a b a",
"Considere a seguinte gramática G = (V, T, P, S), onde:V = {S, X, T, A, B},T = {a, b}P = { S ®e | AB | XB        T ® AB | XB        X® AT    A ® a        B ® bAssinale a alternativa que representa o triângulo de derivação para a palavra aaabb, ao se aplicar o algoritmo CYK.R-XS, TXT, SAAABBaaabb",
"V = {S, X, T, A, B},T = {a, b}P = { S ®e | AB | XB        T ® AB | XB        X® AT    A ® a        B ® bAssinale a alternativa que representa o triângulo de derivação para a palavra aaabbb, ao se aplicar o algoritmo CYK.R-S, TXS, TXS, TAAABBBaaabbb",
"A primeira etapa do algoritmo de Early consiste na construção do primeiro conjunto de produções. Considere a seguinte gramática:G = (V, T, P, E) onde:V = {E, T, F}T = {+, *, [,], x}P = { E ® T | E + T        T ® F | T* F        F ® [E] | x }Seja a cadeia de entrada x*x. Ao se aplicar o algoritmo de Early para esta cadeia, pode-se afirmar que  não faz parte do primeiro conjunto das produções:R_T ®·x/0",
"Considere a seguinte gramática:G = (V, T, P, E) onde:V = {E, T, F}T = {+, *, [,], x}P = { E ® T | E + T    T ® F | T* F    F ® [E] | x }Seja a cadeia de entrada x*x. Ao se aplicar o algoritmo de Early para esta cadeia, na situação em que o primeiro símbolo x da cadeia é gerado, assinale a alternativa que apresenta a produção que não pode gerar o próximo símbolo (*).R-T ® T·/1",
"G = (V, T, P, E) onde:V = {E, T, F}T = {+, *, [,], x}P = { E ® T | E + T        T ® F | T* F        F ® [E] | x }Seja a cadeia de entrada x*x. Ao se aplicar o algoritmo de Early para esta cadeia, na situação em que o primeiro símbolo x da cadeia é gerado, assinale a alternativa que apresenta a produção em x é reduzido a F.R-F ® x·/0",
"Considere a seguinte gramática:G = (V, T, P, E) onde:V = {E, T, F}T = {+, *, [,], x}P = { E ® T | E + T        T ® F | T* F        F ® [E] | x }Seja a cadeia de entrada x*x. Ao se aplicar o algoritmo de Early para esta cadeia, na situação em que o símbolo * da cadeia é gerado, assinale a alternativa que apresenta a produção em * é gerado.R-  T ® T·* F/0",
"Considere a seguinte gramática:G = (V, T, P, E) onde:V = {E, T, F}T = {+, *, [,], x}P = { E ® T | E + T        T ® F | T* F        F ® [E] | x }Seja a cadeia de entrada x*x. Ao se aplicar o algoritmo de Early para esta cadeia, na situação em que o segundo símbolo x da cadeia é gerado, assinale a alternativa que apresenta a produção em x é reduzido a F.R-F ® x·/2 ",
"Considere a seguinte gramática:G = (V, T, P, E) onde:V = {E, T, F}T = {+, *, [,], x}P = { E ® T | E + T        T ® F | T* F        F ® [E] | x }Seja a cadeia de entrada x*x. Ao se aplicar o algoritmo de Early para esta cadeia, assinale a alternativa que assinala que a entrada foi aceita.R- E ® T·/0",
"Sobre gramáticas e linguagens, considere as afirmativas a seguir.I. Uma gramática na Forma Normal de Chomsky pode ser ambígua.II. Uma gramática ambígua pode gerar uma linguagem inerentemente não ambígua.III. Uma gramática na Forma Normal de Greibach pode ser convertida para a Forma Normal de Chomsky.IV. O algoritmo de conversão de Gramática Livre de Contexto para Gramática na Forma Normal de Chomsky pode ser diretamamente aplicado a uma gramática que não seja λ-livre.Assinale a alternativa correta.R-Somente as afirmativas I, II e III são corretas.",
"Considerando as linguagens L = {0n1n2i | n ≥ 0 e i ≥ 0 } e M = {0i 1n2n |  n ≥ 0 e i ≥ 0  }, podese afirmar que:R-	A intersecção das linguagens L e M é uma linguagem dependente de contexto e portanto não pode ser processada por um autômato de pilha.",
"Considere o que se afirma abaixoI. Uma gramática na Forma Normal de Chomsky pode ser ambígua.PORQUEII. O algoritmo de conversão de Gramática Livre de Contexto para Gramática na Forma Normal de Chomsky pode ser diretamamente aplicado a uma gramática que não seja lambda-livre.Assinale a alternativa corretaR-I é verdadeira, mas II é falsa",
"Formas normais desempenham um papel importante na teoria da linguagem  Considere as seguintes afrmações:I . Uma gramática na Forma Normal de Greibach pode ser convertida para a Forma Normal de Chomsky.II. Uma gramática na Forma Normal de Chomsky pode ser ambígua.III. Seja G uma gramática livre de contexto. Então existe uma gramática equivalente G', L(G) = L(G'), que não tem porduções recusrsivas à esquerda.São corretas as afirmações:R-	I, II e III.",
"Considere as seguintes afirmações:I. O algoritmo de conversão de Gramática Livre de Contexto para Gramática na Forma Normal de Chomsky pode ser diretamamente aplicado a uma gramática que não seja lambda livre. (lambda = palavra vazia).II. A palavra vazia não pertence à linguagem gerada por uma gramática na Forma Normal de Chomsky.III. Uma gramática na Forma Normal de Chomsky pode ser ambígua.São corretas as afirmações:R-R-Apenas II e III",
"Considere as seguintes afirmações.I . O algoritmo de conversão de Gramática Livre de Contexto para Gramática na Forma Normal de Chomsky pode ser diretamamente aplicado a uma gramática que não seja lambda-livre. (lambda = palavra vazia).II. A palavra vazia não pertence à linguagem gerada por uma gramática na Forma Normal de Greibach.III. A palavra vazia não pertence à linguagem gerada por uma gramática na Forma Normal de Chomsky.São corretas:R-Apenas II e III.",
"Considere as seguintes afirmaçõesI. Uma gramática na Forma Normal de Chomsky pode ser ambígua.II. Uma gramática ambígua pode gerar uma linguagem inerentemente não ambígua.III. Uma gramática livre de contexto G = (V, T, P, S) é dita estar na Forma Normal de  Chomsky se todas as suas produções são da forma (suponha quie A, B e C são variávies de V e a é terminal de T):  A → BC ou A → aSão corretas as afirmações:R-I, II e III",
"Considere as seguintes afirmaçõesI. Uma gramática na Forma Normal de Chomsky pode ser ambígua.II. Uma gramática ambígua pode gerar uma linguagem inerentemente não ambígua.III. Uma gramática livre de contexto G = (V, T, P, S) é dita estar na Forma Normal de  Chomsky se todas as suas produções são da forma A → aw, na qual A é uma variável de V, a é um terminal de T, e w é uma palavra de V*São corretas as afirmações:R-I, II e III.",
"Em uma Gramática Dependente de Contexto as produções são da forma:R-A® a, onde A Î (VÈT)+ e a Î (V ÈT)* e |A| £ |a|",
"As gramáticas dependentes de contexto podem apresentar suas produções, cujo lado esquerdo apresentam:R-	uma palavra constituída de símbolos terminais e/ou não-terminais;",
"Considere a gramática G definida pelasregras de produção ao lado, em que os símbolos não-terminais são S, A e B, e os símbolos terminais são a e b.S ® ABAB ®AABA ® aB ® b Considere as seguintes afirmações:I - A gramática G é uma gramática dependente de contexto.II - a cadeia aabbb é gerada por essa gramática.III - a gramática G gera a cadeia nula.IV – As palavras da Linguagem L(w) = {w | w = a+b} pertencem à Linguagem gerada pela gramática G.R-R-Apenas I e IV;",
"Assinale a linguagem L definida sobre o alfabeto A = {a, b, c, d} que não pode ser reconhecida por um autômato com uma pilha:R-	L = {w | w = an bn cn , n > 0}",
"Considere G1 = (V, T, P1,S) e G2 = (V, T, P2, S) de tal forma que ambas apresentamV = {S, X, Y}T = {a, b}S é o símbolo inicial .G1 e G2 apresentam os conjuntos de produções P1 e P2, respectivamente como se segue:P1 = { S®  XY  | YXY®  XXYX®  aY®  b }orreta: Considere G1 = (V, T, P1,S) e G2 = (V, T, P2, S) de tal forma que ambas apresentamV = {S, X, Y}T = {a, b}S é o símbolo inicial .G1 e G2 apresentam os conjuntos de produções P1 e P2, respectivamente como se segue:P1 = { S®  XY  | YXY®  XXYX®  aY®  b } P2 = { S®  XY  | YX®  XXYX®  aY®  b } Assinale a alternativa correta:R-G1 é uma gramática dependente  de Contexto e G2 é uma gramática livre de contexto.",
"O Processamento de Linguagem Natural pode se beneficiar do estudo das Linguagens Livres de Contexto, pois permitem uma representação simples da sintaxe.  Por outro lado, considere-se a oração: “O menino viu o cachorro com binóculos”. Trata-se de uma oração sintaticamente correta, porém ambígua. Assinale a alternativa correta:RDeterminar se uma gramática Livre de Contexto é ambígua é um problema não-solucionável.",
"Assinale a alternativa que apresenta um problema passível de ser resolvido pelo estudo das Linguagens Livres de ContextoR-Desenvolvimento de ferramentas que descrevam sintaticamente a linguagem e seus processos de análise.",
"Considere G1 = (V, T, P1,S) e G2 = (V, T, P2, S) de tal forma que ambas apresentamV = {S, X, Y}T = {a, b}S é o símbolo inicial .G1 e G2 apresentam os conjuntos de produções P1 e P2, respectivamente como se segue:P1 = { S®  XY  | YXY®  XXYX®  aY®  b } P2 = { S®  XY  | YX®  XXYX® aY®  baX®  aYb®  b }Assinale a alternativa correta:R-R-G1 é uma gramática dependente  de Contexto e G2 é uma gramática irrestrita",
"Considere as seguintes afirmações:I – Para toda Linguagem Regular, existe um autômato finito que sempre para, qualquer que seja a palavra a ser reconhecida.II – Toda Linguagem Livre de Contexto é Dependente de Contexto;III – Toda Linguagem  Irrestrita é Dependente de Contexto;IV – Toda Linguagem Dependente de Contexto é Livre de Contexto.Estão corretas as afirmações:R-I, III e IV;",
"A aplicação imediata do estudo das Linguagens Regulares e das Linguagens Livres de Contexto é o projeto de Linguagens de Programação e a construção dos seus compiladores. Por outro lado, a componente dependente de contexto presente nas Linguagens de Programação não são tratadas pelos compiladores pelo estudo das gramáticas dependentes de contexto , mas sim por um formalismo denominado Gramática de Atributos, extensão da Gramática Dependente de Contexto. Isto se dá porque:R-Não existe um algoritmo reconhecedor/ aceitador de Linguagens Dependentes de Contexto obtido a partir de uma Linguagem Dependente de Contexto arbitrária;",
"Sobre a hierarquia de Chomsky podemos afirmar que:R-Há linguagens que não são nem livres de contexto nem sensíveis a contexto.",
"Considere as seguintes afirmações;I - Toda linguagem recursiva é também uma linguagem recursivamente enumerável.II - Toda linguagem regular é recursivamente enumerávelIII - Toda linguagem livre de contexto é também sensível a contexto.Assinale a alternativa correta.R-As afirmações I, II e III são verdadeiras.",
"Observe a gramática a seguirS→ aAbbaaAb →aabbbA | abbAb→bbAbAa →BbaabB →BbaB →aASobre esta gramática, assinale a alternativa correta:RÉ irrestrita e aceita a linguagem {anb2nan | n ≥  1.}",
"Com relação às linguagens e seus aceitadores, considere as afirmativas a seguir.I. {wwrev / w∈{a,b}*} é aceita por autômato de pilha determinístico.II. {wcwrev / w∈{a,b}*} é aceita por autômato finito não determinístico.III. {a,b}*-{ww / w∈{a,b}*} é aceita por autômato de pilha não determinístico.IV. {M / M é M.T. e M para} é aceita for Máquina de Turing não determinística.Assinale a alternativa correta.R-R-Somente as afirmativas III e IV são corretas.",
"Dado um inteiro fixo k > 0 e a linguagem L =  {a2ncnbn; n < = k }, considere as seguintes afirmações:I. é uma linguagem livre de contexto, mas não regular.II. L é uma linguagem sensível ao contexto, mas não livre dele.III. L é uma linguagem regular apenas.R-Apenas a afirmativa II é verdadeira",
"Dado um inteiro fixo k > 0 e a linguagem L = {a2ncnbn; n < = k}, podemos afirmar que:I, L é uma linguagem sensível ao contexto, mas não livre dele.II.  L é uma linguagem regular apenas.III.  L é uma linguagem recursivaRApenas I e III são corretas",
"Sobre a hierarquia de Chomsky podemos afirmar que:R-Há linguagens que não são nem livres de contexto nem sensíveis a contexto.",
"regras de produção ao lado, em que os símbolos não-terminais são S, A e B, e os símbolos terminais são a e b.S → ABAB →AABA → aB → bConsidere as seguintes afirmações:I - A gramática G é uma gramática dependente de contexto.II - a cadeia aabbb é gerada por essa gramática.III - a gramática G gera a cadeia nula.IV – As palavras da Linguagem L(w) = {w | w = a+b} pertencem à Linguagem gerada pela gramática G.R-Apenas I e IV;",
]






















$(document).ready(function(){
  $('#entrada').bind('input',function(){
    busca = $(this).val().toLowerCase();
    
    if(busca !== ''){
      var corresponde = false;
      var saida = Array();
      var quantidade = 0;
      for(var key in array){
        
        corresponde = array[key].toLowerCase().indexOf(busca) >= 0;
        if(corresponde){
          saida.push(array[key]);
          quantidade += 1;
        }
      }
      if(quantidade){
        $('#saidaTxt').text('');
        $('#quantidade').html(quantidade+' resultados!<br><br>');
        for(var ind in saida){
           $('#saidaTxt').append("<li>"+saida[ind]+"</li>"+"<br>");
        }
        
      }else{
        $('#quantidade').html('');
        $('#saidaTxt').text('Nenhum resultado...');
      }
    
    }else{
      $('#quantidade').html('');
      $('#saidaTxt').text('Nenhum resultado...');
    }
    
    
    
  });
});
}
